name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: justificantes_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: justificantes_db

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar cliente MySQL
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Esperar a que MySQL esté listo
        run: |
          echo "Esperando a que MySQL esté listo..."
          for i in {1..30}; do
            if mysqladmin ping -h $DB_HOST -u$DB_USER -p$DB_PASSWORD --silent; then
              echo "MySQL listo!"
              break
            fi
            echo "Esperando..."
            sleep 5
          done

      - name: Crear tabla de pruebas
        run: |
          mysql -h $DB_HOST -u$DB_USER -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
          mysql -h $DB_HOST -u$DB_USER -p$DB_PASSWORD $DB_NAME -e "
            CREATE TABLE IF NOT EXISTS solicitudes (
              id INT AUTO_INCREMENT PRIMARY KEY,
              nombre VARCHAR(100),
              grupo VARCHAR(50),
              motivo TEXT,
              fecha_ausencia DATE,
              fecha_solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
          "

      - name: Instalar dependencias del backend
        run: |
          cd backend
          npm install

      - name: Dar permisos a Jest
        run: chmod +x ./backend/node_modules/.bin/jest

      - name: Verificar Jest
        run: |
          cd backend
          npx jest --version
          ls -la ./node_modules/.bin/

      - name: Ejecutar tests
        run: |
          cd backend
          npx jest --runInBand
